name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  # Building using the github runner environment directly.
  xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select latest XCode version
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
    - name: Set CXX=clang++
      run: echo "CC=clang" >> $GITHUB_ENV
    - name: Set CXX=clang
      run: echo "CXX=clang++" >> $GITHUB_ENV
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -G "Xcode" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest G++/GCC version
      run: brew install gcc-11
    - name: Set CXX=g++-11
      run: echo "CXX=g++-11" >> $GITHUB_ENV
    - name: Set C=gcc-11
      run: echo "C=gcc-11" >> $GITHUB_ENV
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
