name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
      
jobs:
  # Building using the github runner environement directly.
  xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check CMake
      run: cmake --version
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -G "Xcode" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check CMake
      run: cmake --version
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
