name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  visual-studio:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  make:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -S. -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
